### ISSUE TITLE
Are the pair of the images synchronized?

### ISSUE THREAD

**Issue by aseyfi** [joshvillbrandt/elp-stereo-camera-ros-pkg#1]
Are the published stereo images synchronized?
Thank You,

**Comment by joshvillbrandt** [comment]
As far as I know, the ELP-1MP2CAM001 camera does not support hardware-level synchronization.

The [stereo_image_proc.launch](https://github.com/joshvillbrandt/elp-stereo-camera-ros-pkg/blob/master/launch/stereo_image_proc.launch#L8) file in this repository makes use of the `approximate_sync` flag.
