### ISSUE TITLE
 VIDIOC_STREAMON error 5, Input/output erro

### ISSUE THREAD

**Issue by GnawXam** [joshvillbrandt/elp-stereo-camera-ros-pkg#2]
I am unable to get the camera to work. Since there is no ros-indigo-elp-stereo-camera package, I followed the steps in the Github. At first ROS doesn't recognize elp-stereo-camera as a package, but after some time just leaving it alone, it recognized it. I then used 

> roslaunch elp_stereo_camera elp_stereo_camera.launch

And I received these errors

> [ERROR] [1468606140.257202141]: VIDIOC_STREAMON error 5, Input/output error
> [ERROR] [1468606140.265184868]: VIDIOC_STREAMON error 5, Input/output error
> [el/left-2] process has died [pid 19567, exit code 1, cmd /opt/ros/indigo/lib/usb_cam/usb_cam_node __name:=left __log:=/home/max/.ros/log/2d3e867e-4ab7-11e6-82ce-08002755c1aa/elp-left-2.log].
> log file: /home/max/.ros/log/2d3e867e-4ab7-11e6-82ce-08002755c1aa/elp-left-2_.log
> [elp/right-3] process has died [pid 19568, exit code 1, cmd /opt/ros/indigo/lib/usb_cam/usb_cam_node __name:=right __log:=/home/max/.ros/log/2d3e867e-4ab7-11e6-82ce-08002755c1aa/elp-right-3.log].
> log file: /home/max/.ros/log/2d3e867e-4ab7-11e6-82ce-08002755c1aa/elp-right-3_.log

When I try to call the camera with guvcview, I get these:

> vid:05a3 
> pid:9601 
> driver:uvcvideo
> checking format: 1196444237
> VIDIOC_G_COMP:: Inappropriate ioctl for device
> fps is set to 1/30
> drawing controls
> 
> libv4l2: error turning on stream: Input/output error
> VIDIOC_STREAMON - Unable to start capture: Input/output error
> fps is set to 1/30
> Checking video mode 640x480@32bpp : OK 
> libv4l2: error turning on stream: Input/output error
> VIDIOC_STREAMON - Unable to start capture: Input/output error
> libv4l2: error turning on stream: Input/output error
> VIDIOC_STREAMON - Unable to start capture: Input/output error

So it looks like I just can't get the camera to work, for some reason. I tried looking up these errors, but with little luck. I wonder if it's a virtual machine issue, or I installed something incorrectly?

Any thoughts?
Thanks.

**Comment by joshvillbrandt** [comment]
Hi @GnawXam,

Indeed, I haven't had a chance to formally release this package for any of the ROS distributions. :/

It looks like the individual `usb_cam_node`s are crashing. Here are some things you can try:
- Can you view both of the cameras using a webcam app? I think Ubuntu has a GUI webcam app installed by default, otherwise you can download more from the store.
- Can you run a `usb_cam_node` for one of the images from the command line?

Otherwise, I'd suggest using Google to search for that error. I don't think the error itself is related to ROS, so you have a pretty good chance of finding some answers on the web.

Let us know what you find out!

**Comment by GnawXam** [comment]
Hi @joshvillbrandt 

So I'm running Windows 10 and VM Virtual Box with Ubuntu 14.04.
The cameras 1 and 2 appear on Windows and can stream videos fine.
The devices do show up on VM and I can select them, but when I use the defautl GUI apps like Cheese or Guvcvidew, nothing shows up, even though the cameras are selected. I run into the ioctl issue.

I tried to see if usb_cam works but I run into a calibration error, saying that it is "Unable to open camera calibration file."

It certainly seems like a setup issue, somewhere, but I'm not sure what. Googling has not been fruitful - some of the solutions for people do not work for me with this camera. So I was hoping that you can share some of your experiences or steps, maybe that'd help.

**Comment by GnawXam** [comment]
I also tried to use your camera calibration file in place of the one usb_cam is looking for. But then there's still an error, same as the one I saw when launching your package.

**Comment by GnawXam** [comment]
It turns out for VM it is necessary to enable the correct USB driver (2.0 or 3.0) in order to interface with the camera. This issue appears to be solved.
